name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t django-backend:test ./backend

      - name: Run tests in Docker container
        run: |
          docker run --rm django-backend:test python manage.py test api.tests


  deploy-backend:
    name: Deploy to EC2
    needs: test-backend
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start SSH connection
        uses: webfactory/ssh-agent@v0.9.0 # This is a GitHub action to start an SSH agent
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy application
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_APP_DIR: ${{ secrets.EC2_APP_DIR }}
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << EOF
            set -e

            cd $EC2_APP_DIR

            echo "ðŸ“¥ Pulling latest code"
            git pull origin master

            echo "ðŸ³ Building Docker image"
            docker-compose build backend

            echo "ðŸ—„ Running migrations & collectstatic"
            docker-compose run --rm backend python manage.py migrate --noinput
            docker-compose run --rm backend python manage.py collectstatic --noinput

            echo "ðŸ”„ Restarting Docker containers"
            docker-compose up -d --build backend
          EOF
